### ISSUE TITLE
Update code 

### ISSUE THREAD

**Issue by markdegrootnl** [coenjacobs/eloquent-composite-primary-keys#4]
Please update the package with the code from https://github.com/mopo922/LaravelTreats

**Comment by coenjacobs** [comment]
I have decided to make this project read-only and not further work on this. There are a bunch of performance related downsides when doing this in Laravel, which make it no longer fun and rewarding for me to work on.

In case you still want to use this functionality in Laravel, you can have a look at the [LaravelTreats package](https://github.com/mopo922/LaravelTreats/tree/master/src/Model#laraveltreatsmodeltraitshascompositprimarykey) which contains similar functionality.
