### ISSUE TITLE
Error on updating

### ISSUE THREAD

**Issue by vservin** [coenjacobs/eloquent-composite-primary-keys#5]
I've been debugging an update of a model, this is my problem:
If you try to update a specific model on Eloquent, if you edit the primary key field, on the "where" statement it places the old value of the primary key. Example: update myTable set primary = 'newValue' where primary = 'oldValue';
While using the compositekeys package, if I try doing the same thing, edit one or 'n' fields that are part of the primary key, in the where statement it takes the new values, not the old, therefore, it doesn't update nothing. Example where updating only one field: update myTable set primary_1 = 'newValue1', primary_2 = 'oldValue2'  where primary_1 = 'newValue1' and primary_2 = 'oldValue2';

**Comment by coenjacobs** [comment]
I have decided to make this project read-only and not further work on this. There are a bunch of performance related downsides when doing this in Laravel, which make it no longer fun and rewarding for me to work on.

In case you still want to use this functionality in Laravel, you can have a look at the [LaravelTreats package](https://github.com/mopo922/LaravelTreats/tree/master/src/Model#laraveltreatsmodeltraitshascompositprimarykey) which contains similar functionality.
