### ISSUE TITLE
Error On Replicate

### ISSUE THREAD

**Issue by Pamith** [coenjacobs/eloquent-composite-primary-keys#8]
While trying to replicate the model object it throws some error

**Comment by coenjacobs** [comment]
I have decided to make this project read-only and not further work on this. There are a bunch of performance related downsides when doing this in Laravel, which make it no longer fun and rewarding for me to work on.

In case you still want to use this functionality in Laravel, you can have a look at the [LaravelTreats package](https://github.com/mopo922/LaravelTreats/tree/master/src/Model#laraveltreatsmodeltraitshascompositprimarykey) which contains similar functionality.
